# Generated by Django 4.0.6 on 2022-07-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=60)),
                ('receiver', models.CharField(max_length=60)),
                ('body', models.CharField(max_length=160)),
                ('sent', models.DateTimeField()),
                ('received', models.BooleanField()),
            ],
        ),
    ]
