# Generated by Django 4.0.6 on 2022-07-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapi', '0002_message_created_message_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='received',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
